# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c0eefc98e41edf205c183823f48779dfcea7e36c346c3a40c9c70f552b0bbb555a5fddd2452db6461f5a1f54bc52c4e337f1b5d873eda25f5cb6f4ae61bb585

test:
  secret_key_base: 7e9b49e4176e764d085b9b62513b9ce940019271fbc611ad42a1b974a0df32cb9563346d48645160ffaee1b7fae3be879a3c35d0348f4236b756f0d8036da35d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
